### ISSUE TITLE
[BE] User(사용자) CRUD

### ISSUE THREAD

**Issue by SalguJam** [Logic-Breakers/L-B-Server#2]
## 요구사항 정의서 ID
MEM01_LOGIN01 생성(회원가입)
MEM06_SEARCH01 조회
MEM07_UPDATE01 수정
MEM04_DELETE01 삭제

## 구현해야 할 기능
- [x] UserEntity
- [x] UserService
- [x] UserController
- [x] UserRepository
- [x] UserMapper
- [x] UserDto

**Comment by KSJ-0** [comment]
테스트 완료해서 이슈 닫습니다 security 적용은 새 이슈 열게요!
